// flow-typed signature: 6dbac4d415cb0d20d29fae3210f14cdd
// flow-typed version: <<STUB>>/@types/jest_v^24.0.18/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest' {
  declare module.exports: any;
}
