// flow-typed signature: 3feba7064d41edcbc3d7bdcedb7204a0
// flow-typed version: <<STUB>>/reactotron-redux_v^3.1.1/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reactotron-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reactotron-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reactotron-redux/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reactotron-redux/dist/index' {
  declare module.exports: $Exports<'reactotron-redux/dist'>;
}
declare module 'reactotron-redux/dist/index.js' {
  declare module.exports: $Exports<'reactotron-redux/dist'>;
}
