// flow-typed signature: 78d857385ef269549ff6c2d984194ba8
// flow-typed version: <<STUB>>/reactotron-react_v^1.0.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reactotron-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reactotron-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reactotron-react/reactotron.native' {
  declare module.exports: any;
}

declare module 'reactotron-react/reactotron.web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reactotron-react/index' {
  declare module.exports: $Exports<'reactotron-react'>;
}
declare module 'reactotron-react/index.js' {
  declare module.exports: $Exports<'reactotron-react'>;
}
declare module 'reactotron-react/reactotron.native.js' {
  declare module.exports: $Exports<'reactotron-react/reactotron.native'>;
}
declare module 'reactotron-react/reactotron.web.js' {
  declare module.exports: $Exports<'reactotron-react/reactotron.web'>;
}
